### ISSUE TITLE
I18n.interpolate missing in 0.5.2/0.5.3

### ISSUE THREAD

**Issue by shioyama** [svenfuchs/i18n#232]
In the [commits between 0.5.0 and 0.5.2](https://github.com/svenfuchs/i18n/compare/v0.5.0...v0.5.2), the `I18n.interpolate` method seems to have disappeared:

```
irb(main):001:0> require 'i18n'
=> true
irb(main):002:0> I18n::VERSION
=> "0.5.3"
irb(main):003:0> I18n.interpolate
NoMethodError: undefined method `interpolate' for I18n:Module
        from (irb):3
        from /Users/chris/.rbenv/versions/2.0.0-p247/bin/irb:12:in `<main>'
```

[Globalize](https://github.com/globalize/globalize) still supports Rails 3.0 so we need this (see our [failing tests](https://travis-ci.org/globalize/globalize/builds/15272724)). Was this removal intentional? Is there a workaround? I've dug through the code a bit and found that I can replace it with `%`, but this doesn't seem to work in ruby 1.8.7. 

Any suggestions welcome. Thanks!

**Comment by radar** [comment]
This method exists in 0.7.0 and master versions of i18n.
